model = "gpt-5.2"
model_reasoning_effort = "medium"

[features]
rmcp_client = true

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_TOKEN_MCP"

# [mcp_servers.nx-mcp]
# command = "npx"
# args = ["nx", "mcp"]

[mcp_servers.sentry]
url = "https://mcp.sentry.dev/mcp"
startup_timeout_sec = 120

[mcp_servers.atlassian]
command = "bunx"
args = ["mcp-remote@0.1.31", "https://mcp.atlassian.com/v1/sse"]
startup_timeout_sec = 120

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
