[features]
rmcp_client = true

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_TOKEN_MCP"

# [mcp_servers.nx-mcp]
# command = "npx"
# args = ["nx", "mcp"]

[mcp_servers.sentry]
url = "https://mcp.sentry.dev/mcp"
startup_timeout_sec = 120

[mcp_servers.atlassian]
command = "npx"
args = ["-y", "mcp-remote@latest", "https://mcp.atlassian.com/v1/sse"]
startup_timeout_sec = 120
