model = "gpt-5.2"
model_reasoning_effort = "medium"

[features]
web_search_request = true
rmcp_client = true

[sandbox_workspace_write]
network_access = true

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_TOKEN_MCP"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
env_http_headers = { "CONTEXT7_API_KEY" = "CONTEXT7_API_KEY" }
